export const POKEMON_SETS = [
  "Base Set",
  "Base Set 2",
  "Jungle",
  "Fossil",
  "Team Rocket",
  "Gym Heroes",
  "Gym Challenge",
  "Neo Genesis",
  "Neo Discovery",
  "Neo Revelation",
  "Neo Destiny",
  "Legendary Collection",
  "Expedition Base Set",
  "Aquapolis",
  "Skyridge",
  "Ruby & Sapphire",
  "Sandstorm",
  "Dragon",
  "Neo Revelation",    // già citato — ma attenzione ai duplicati
  "Neo Destiny",
  "Hidden Legends",
  "Unseen Forces",
  "Delta Species",
  "Legend Maker",
  "Holon Phantoms",
  "Unleashed",
  "Triumphant",
  "Supreme Victors",
  "Stormfront",
  "Platinum",
  "Rising Rivals",
  "Supreme Victors",
  "Arceus",
  "Diamond & Pearl",
  "Mysterious Treasures",
  "Secret Wonders",
  "Great Encounters",
  "Majestic Dawn",
  "Legends Awakened",
  "Legends Unleashed",
  "Diamond & Pearl - Call of Legends",
  "Baseriquest/BASE",
  "HeartGold & SoulSilver",
  "Undaunted",
  "Triumph",
  "Forbidden Light",
  "Steam Siege",
  "Evolutions",
  "Shining Legends",
  "Hidden Fates",
  "Sun & Moon",
  "Guardians Rising",
  "Burning Shadows",
  "Crimson Invasion",
  "Ultra Prism",
  "Celestial Storm",
  "Lost Thunder",
  "Team Up",
  "Unbroken Bonds",
  "Unified Minds",
  "Rebel Clash",
  "Darkness Ablaze",
  "Sword & Shield",
  "Rebel Clash",
  "Champion's Path",
  "Vivid Voltage",
  "Shining Fates",
  "Battle Styles",
  "Chilling Reign",
  "Evolving Skies",
  "Fusion Strike",
  "Brilliant Stars",
  "Astral Radiance",
  "Lost Origin",
  "Silver Tempest",
  "Crown Zenith",
  "Scarlet & Violet - Paldea Evolved",
  "Scarlet & Violet - Obsidian Flames",
  "Scarlet & Violet - Violet Expanse",
  "Scarlet & Violet - Paradox Rift",
  "Scarlet & Violet - Lost Zone",
  // aggiungi altri se ti servono
];

